package i18n

// Карточка зоны (этап 4): надписи — как в Loc.table мак-версии (App.swift),
// только %@ и %d заменены на %s. Виды дорог, которые на маке подписаны
// пустой строкой (обычные и «чёрные» дороги), здесь не заведены вовсе:
// пустой перевод словарь не пропускает, а zonecard.Kind и страница
// понимают отсутствие ключа как «без подписи». Столбцы — как у Table.
func init() {
	for k, v := range cardTable {
		Table[k] = v
	}
}

var cardTable = map[string][9]string{
	// качество зоны
	"q.safe":     {"синяя зона", "safe zone", "zona azul", "niebieska strefa", "blaue Zone", "mavi bölge", "zone bleue", "zona azul", "zona blu"},
	"q.yellow":   {"жёлтая зона", "yellow zone", "zona amarilla", "żółta strefa", "gelbe Zone", "sarı bölge", "zone jaune", "zona amarela", "zona gialla"},
	"q.red":      {"красная зона", "red zone", "zona roja", "czerwona strefa", "rote Zone", "kırmızı bölge", "zone rouge", "zona vermelha", "zona rossa"},
	"q.black":    {"чёрная зона", "black zone", "zona negra", "czarna strefa", "schwarze Zone", "siyah bölge", "zone noire", "zona preta", "zona nera"},
	"q.city":     {"город", "city", "ciudad", "miasto", "Stadt", "şehir", "ville", "cidade", "città"},
	"q.island":   {"остров", "island", "isla", "wyspa", "Insel", "ada", "île", "ilha", "isola"},
	"q.mists":    {"туманы", "the Mists", "las Nieblas", "Mgły", "die Nebel", "Sisli Diyar", "les Brumes", "as Brumas", "le Nebbie"},
	"q.instance": {"подземелье", "instance", "instancia", "instancja", "Instanz", "instance", "instance", "instância", "istanza"},
	"q.roads":    {"дороги Авалона", "Roads of Avalon", "caminos de Avalon", "Drogi Avalonu", "Straßen von Avalon", "Avalon Yolları", "Routes d'Avalon", "Estradas de Avalon", "Strade di Avalon"},
	"q.other":    {"зона", "zone", "zona", "strefa", "Zone", "bölge", "zone", "zona", "zona"},
	"q.grade":    {"качество %s", "quality %s", "calidad %s", "jakość %s", "Qualität %s", "kalite %s", "qualité %s", "qualidade %s", "qualità %s"},

	// виды дорог
	"type.TUNNEL_HIDEOUT":      {"дорога убежищ", "hideout road", "camino de refugios", "droga kryjówek", "Unterschlupf-Straße", "sığınak yolu", "route des repaires", "estrada de esconderijos", "strada dei nascondigli"},
	"type.TUNNEL_HIDEOUT_DEEP": {"глубокая дорога убежищ", "deep hideout road", "camino de refugios profundo", "głęboka droga kryjówek", "tiefe Unterschlupf-Straße", "derin sığınak yolu", "route des repaires profonde", "estrada de esconderijos profunda", "strada dei nascondigli profonda"},
	"type.TUNNEL_DEEP":         {"глубокая", "deep", "profunda", "głęboka", "tief", "derin", "profonde", "profunda", "profonda"},
	"type.TUNNEL_DEEP_RAID":    {"глубокая рейдовая", "deep raid", "profunda de incursión", "głęboka rajdowa", "tief, Raid", "derin baskın", "profonde de raid", "profunda de raide", "profonda da raid"},
	"type.TUNNEL_ROYAL":        {"королевская", "royal", "real", "królewska", "königlich", "kraliyet", "royale", "real", "reale"},
	"type.TUNNEL_ROYAL_RED":    {"королевская красная", "royal red", "real roja", "królewska czerwona", "königlich rot", "kraliyet kırmızı", "royale rouge", "real vermelha", "reale rossa"},

	// ресурсы, лагеря, сундуки, подземелья
	"res.FIBER":            {"волокно", "fiber", "fibra", "włókno", "Faser", "lif", "fibre", "fibra", "fibre"},
	"res.HIDE":             {"шкуры", "hide", "pieles", "skóry", "Fell", "kürk", "peau", "pelego", "pelle"},
	"res.ORE":              {"руда", "ore", "mineral", "ruda", "Erz", "cevher", "minerai", "minério", "minerali"},
	"res.ROCK":             {"камень", "stone", "piedra", "kamień", "Stein", "taş", "pierre", "pedra", "pietra"},
	"res.WOOD":             {"дерево", "wood", "madera", "drewno", "Holz", "odun", "bois", "madeira", "legno"},
	"camp.group":           {"групповой", "group", "grupal", "grupowy", "Gruppe", "grup", "de groupe", "em grupo", "di gruppo"},
	"camp.solo_small":      {"соло малый", "small solo", "solo pequeño", "solo mały", "Solo klein", "küçük solo", "petit solo", "solo pequeno", "solo piccolo"},
	"camp.solo_big":        {"соло большой", "big solo", "solo grande", "solo duży", "Solo groß", "büyük solo", "grand solo", "solo grande", "solo grande"},
	"camp.raid_small":      {"рейдовый малый", "small raid", "incursión pequeña", "rajdowy mały", "Raid klein", "küçük baskın", "petit raid", "raide pequeno", "raid piccolo"},
	"camp.raid_big":        {"рейдовый большой", "big raid", "incursión grande", "rajdowy duży", "Raid groß", "büyük baskın", "grand raid", "raide grande", "raid grande"},
	"chest.small":          {"малый", "small", "pequeño", "mała", "klein", "küçük", "petit", "pequeno", "piccolo"},
	"chest.small_elite":    {"малый элитный", "small elite", "pequeño élite", "mała elitarna", "klein, Elite", "küçük elit", "petit élite", "pequeno de elite", "piccolo d'élite"},
	"chest.medium_veteran": {"средний ветеранский", "medium veteran", "mediano veterano", "średnia weterańska", "mittel, Veteran", "orta kıdemli", "moyen vétéran", "médio veterano", "medio veterano"},
	"chest.medium_elite":   {"средний элитный", "medium elite", "mediano élite", "średnia elitarna", "mittel, Elite", "orta elit", "moyen élite", "médio de elite", "medio d'élite"},
	"dng.group":            {"групповое", "group", "grupal", "grupowy", "Gruppe", "grup", "de groupe", "em grupo", "di gruppo"},
	"dng.solo":             {"соло", "solo", "solo", "solo", "Solo", "solo", "solo", "solo", "solo"},
	"dng.raid":             {"рейдовое", "raid", "incursión", "rajdowy", "Raid", "baskın", "de raid", "de raide", "da raid"},

	// карточка
	"zn.cardTitle":    {"КАРТОЧКА ЗОНЫ", "ZONE CARD", "TARJETA DE ZONA", "KARTA STREFY", "ZONENKARTE", "BÖLGE KARTI", "FICHE DE ZONE", "FICHA DA ZONA", "SCHEDA ZONA"},
	"zn.hint":         {"Наведись в игре на портал и нажми %s", "Point at a portal in game and press %s", "Apunta a un portal en el juego y pulsa %s", "Najedź w grze na portal i naciśnij %s", "Zeig im Spiel auf ein Portal und drück %s", "Oyunda bir portala gel ve %s tuşuna bas", "Vise un portail en jeu et appuie sur %s", "Aponte para um portal no jogo e aperte %s", "Punta un portale nel gioco e premi %s"},
	"zn.keyOff":       {"Кнопка карточки выключена в настройках.", "The zone card button is off in the settings.", "El botón de la tarjeta está desactivado en los ajustes.", "Przycisk karty jest wyłączony w ustawieniach.", "Der Knopf für die Zonenkarte ist in den Einstellungen aus.", "Kart düğmesi ayarlarda kapalı.", "Le bouton de la fiche est désactivé dans les paramètres.", "O botão da ficha está desligado nas configurações.", "Il pulsante della scheda è disattivato nelle impostazioni."},
	"zn.busy":         {"снимаю…", "capturing…", "capturando…", "robię zrzut…", "nehme auf…", "görüntü alınıyor…", "capture…", "capturando…", "catturo…"},
	"zn.shot":         {"снято %s", "captured %s", "capturado %s", "zrzut %s", "aufgenommen %s", "alındı %s", "capturé %s", "capturado %s", "catturato %s"},
	"zn.noTooltip":    {"Под курсором не портал дорог. Наведись на воронку и повтори.", "No roads portal under the cursor. Point at one and retry.", "No hay portal bajo el cursor. Apunta a uno y repite.", "Pod kursorem nie ma portalu dróg. Najedź na lej i spróbuj ponownie.", "Unter dem Cursor ist kein Straßenportal. Zeig auf eines und versuch es nochmal.", "İmlecin altında yol portalı yok. Birinin üstüne gel ve tekrar dene.", "Pas de portail des routes sous le curseur. Vise-en un et réessaie.", "Não há portal das estradas sob o cursor. Aponte para um e tente de novo.", "Sotto il cursore non c'è un portale delle strade. Puntane uno e riprova."},
	"zn.failed":       {"Снимок не вышел: %s", "Capture failed: %s", "Fallo la captura: %s", "Zrzut się nie udał: %s", "Aufnahme fehlgeschlagen: %s", "Görüntü alınamadı: %s", "La capture a échoué : %s", "A captura falhou: %s", "Cattura non riuscita: %s"},
	"zn.ocrFailed":    {"Распознавание текста не вышло: %s", "Text recognition failed: %s", "Falló el reconocimiento de texto: %s", "Rozpoznawanie tekstu się nie udało: %s", "Texterkennung fehlgeschlagen: %s", "Metin tanıma başarısız: %s", "La reconnaissance de texte a échoué : %s", "O reconhecimento de texto falhou: %s", "Riconoscimento del testo non riuscito: %s"},
	"zn.unknown":      {"Не узнал зону: «%s»", "Zone not recognised: “%s”", "Zona no reconocida: «%s»", "Nie rozpoznano strefy: „%s”", "Zone nicht erkannt: „%s“", "Bölge tanınmadı: “%s”", "Zone non reconnue : « %s »", "Zona não reconhecida: “%s”", "Zona non riconosciuta: “%s”"},
	"zn.blank":        {"Снимок пустой — похоже, игра в полноэкранном режиме. Переключи игру в «окно без рамки».", "The capture is empty — the game seems to be in fullscreen mode. Switch the game to borderless window.", "La captura está vacía: parece que el juego está en pantalla completa. Cambia el juego a ventana sin bordes.", "Zrzut jest pusty — gra chyba działa w trybie pełnoekranowym. Przełącz grę na „okno bez ramki”.", "Die Aufnahme ist leer — das Spiel scheint im Vollbild zu laufen. Stell das Spiel auf „Rahmenloses Fenster“ um.", "Görüntü boş — oyun tam ekran modunda gibi. Oyunu “kenarlıksız pencere” moduna al.", "La capture est vide — le jeu semble être en plein écran. Passe le jeu en « fenêtre sans bordure ».", "A captura está vazia — parece que o jogo está em tela cheia. Mude o jogo para “janela sem bordas”.", "La cattura è vuota — sembra che il gioco sia a schermo intero. Passa il gioco a “finestra senza bordi”."},
	"zn.blankShort":   {"Переключи игру в окно без рамки", "Switch the game to borderless window", "Cambia el juego a ventana sin bordes", "Przełącz grę na okno bez ramki", "Stell das Spiel auf rahmenloses Fenster um", "Oyunu kenarlıksız pencere moduna al", "Passe le jeu en fenêtre sans bordure", "Mude o jogo para janela sem bordas", "Passa il gioco a finestra senza bordi"},
	"zn.blankTitle":   {"Карточка зоны: снимок пустой", "Zone card: empty capture", "Tarjeta de zona: captura vacía", "Karta strefy: pusty zrzut", "Zonenkarte: leere Aufnahme", "Bölge kartı: boş görüntü", "Fiche de zone : capture vide", "Ficha da zona: captura vazia", "Scheda zona: cattura vuota"},
	"zn.noRef":        {"Справочник зон не прочитался", "Zone reference failed to load", "No se pudo leer el catálogo de zonas", "Nie udało się wczytać spisu stref", "Das Zonenverzeichnis ließ sich nicht laden", "Bölge rehberi yüklenemedi", "Impossible de charger le répertoire des zones", "Não deu para carregar o catálogo de zonas", "Impossibile caricare l'elenco delle zone"},
	"zn.mapHint":      {"Тултип в игре читается плохо — точнее всего на карте мира (M): наведись на портал там.", "The in-game tooltip reads poorly — the world map (M) is most accurate: point at the portal there.", "El tooltip en el juego se lee mal: lo más preciso es el mapa del mundo (M); apunta al portal allí.", "Tooltip w grze czyta się słabo — najdokładniej na mapie świata (M): najedź tam na portal.", "Der Tooltip im Spiel liest sich schlecht — am genauesten ist die Weltkarte (M): Zeig dort auf das Portal.", "Oyundaki ipucu kötü okunuyor — en doğrusu dünya haritası (M): portala orada gel.", "L'infobulle en jeu se lit mal — la carte du monde (M) est la plus précise : vise le portail là-bas.", "A dica de tela no jogo se lê mal — o mapa do mundo (M) é o mais preciso: aponte para o portal lá.", "Il tooltip nel gioco si legge male — la mappa del mondo (M) è la più precisa: punta lì il portale."},
	"zn.mapHintTitle": {"Карточка зоны: не прочитано", "Zone card: not read", "Tarjeta de zona: no leída", "Karta strefy: nie odczytano", "Zonenkarte: nicht gelesen", "Bölge kartı: okunamadı", "Fiche de zone : non lue", "Ficha da zona: não lida", "Scheda zona: non letta"},
	"zn.doubt":        {"Похоже на эту, но уверенности нет — рядом %s", "Looks like this one, but not sure — %s is close", "Parece esta, pero sin certeza — %s está cerca", "Wygląda na tę, ale bez pewności — blisko jest %s", "Sieht nach dieser aus, aber nicht sicher — %s ist ähnlich", "Bu gibi görünüyor ama emin değilim — %s de yakın", "Ça ressemble à celle-ci, mais sans certitude — %s est proche", "Parece esta, mas sem certeza — %s está perto", "Sembra questa, ma senza certezza — %s è vicina"},
	"zn.points":       {"точки", "spots", "puntos", "punkty", "Punkte", "noktalar", "points", "pontos", "punti"},
	"zn.biome":        {"ресурсы", "resources", "recursos", "surowce", "Ressourcen", "kaynaklar", "ressources", "recursos", "risorse"},
	"zn.mainRes":      {"основной ресурс биома", "the biome's main resource", "recurso principal del bioma", "główny surowiec biomu", "Hauptressource des Bioms", "biyomun ana kaynağı", "la ressource principale du biome", "o recurso principal do bioma", "la risorsa principale del bioma"},
	"zn.nodes":        {"на них", "on them", "en ellos", "na nich", "darauf", "üzerlerinde", "dessus", "neles", "su di essi"},
	"zn.camps":        {"лагеря", "camps", "campamentos", "obozy", "Lager", "kamplar", "camps", "acampamentos", "accampamenti"},
	"zn.dungeons":     {"данжи", "dungeons", "mazmorras", "lochy", "Dungeons", "zindanlar", "donjons", "masmorras", "dungeon"},
	"zn.mists":        {"есть выход в город туманов", "exit to the Mists city", "salida a la ciudad de las Nieblas", "jest wyjście do miasta Mgieł", "Ausgang zur Stadt der Nebel", "Sisli Diyar şehrine çıkış var", "sortie vers la ville des Brumes", "saída para a cidade das Brumas", "uscita verso la città delle Nebbie"},
	"zn.portal":       {"портал на %s", "portal for %s", "portal para %s", "portal na %s", "Portal für %s", "%s kişilik portal", "portail pour %s", "portal para %s", "portale per %s"},
	"zn.closes":       {"закроется через %s", "closes in %s", "cierra en %s", "zamknie się za %s", "schließt in %s", "%s içinde kapanır", "ferme dans %s", "fecha em %s", "si chiude tra %s"},
	"zn.unstable":     {"нестабильный путь · в один конец", "unstable road · one-way", "camino inestable · solo ida", "niestabilna droga · w jedną stronę", "instabile Straße · nur in eine Richtung", "dengesiz yol · tek yön", "route instable · aller simple", "estrada instável · só ida", "strada instabile · solo andata"},
	"zn.closesGroup":  {"закроется для группы через %s", "closes to your party in %s", "se cierra para tu grupo en %s", "zamknie się dla drużyny za %s", "schließt sich für deine Gruppe in %s", "grubun için %s içinde kapanır", "ferme pour ton groupe dans %s", "fecha para o seu grupo em %s", "si chiude per il tuo gruppo tra %s"},
	"zn.closed":       {"портал уже закрылся", "the portal has closed", "el portal ya se cerró", "portal już się zamknął", "das Portal hat sich geschlossen", "portal zaten kapandı", "le portail s'est fermé", "o portal já fechou", "il portale si è già chiuso"},
	"t.hm":            {"%s ч %s м", "%s h %s m", "%s h %s min", "%s h %s min", "%s Std. %s Min.", "%s sa %s dk", "%s h %s min", "%s h %s min", "%s h %s min"},
	"zn.none":         {"нет", "none", "no hay", "brak", "keine", "yok", "aucun", "nenhum", "nessuno"},
	"zn.risk":         {"Чёрный экран был в %s из %s твоих переходов в эту зону", "Black screen in %s of your %s moves into this zone", "Pantalla negra en %s de tus %s pasos a esta zona", "Czarny ekran był w %s z %s twoich przejść do tej strefy", "Schwarzbild bei %s von %s deiner Wechsel in diese Zone", "Bu bölgeye geçişlerinde siyah ekran: %s / %s", "Écran noir dans %s de tes %s passages vers cette zone", "Tela preta em %s das suas %s passagens para esta zona", "Schermo nero in %s dei tuoi %s passaggi verso questa zona"},
	"zn.riskNote":     {"по твоей истории переходов — это вероятность, не гарантия", "from your own move history — a probability, not a guarantee", "según tu historial de pasos: es una probabilidad, no una garantía", "według twojej historii przejść — to prawdopodobieństwo, nie gwarancja", "aus deinem eigenen Wechselverlauf — eine Wahrscheinlichkeit, keine Garantie", "kendi geçiş geçmişine göre — bu bir olasılık, garanti değil", "d'après ton propre historique de passages — une probabilité, pas une garantie", "pelo seu próprio histórico de passagens — uma probabilidade, não uma garantia", "dalla tua cronologia di passaggi — una probabilità, non una garanzia"},
	"zn.privacy":      {"Снимок области у курсора остаётся на компьютере: текст читает OCR Windows, в интернет картинка не уходит.", "The capture of the area around the cursor stays on your computer: Windows OCR reads the text, the image never goes online.", "La captura alrededor del cursor se queda en tu equipo: el OCR de Windows lee el texto y la imagen no sale a internet.", "Zrzut obszaru przy kursorze zostaje na komputerze: tekst czyta OCR Windows, obraz nie idzie do internetu.", "Die Aufnahme um den Cursor bleibt auf deinem Computer: Den Text liest die Windows-OCR, das Bild geht nie ins Internet.", "İmlecin etrafındaki görüntü bilgisayarında kalır: metni Windows OCR okur, görüntü asla internete gitmez.", "La capture autour du curseur reste sur ton ordinateur : l'OCR de Windows lit le texte, l'image ne part jamais sur Internet.", "A captura em volta do cursor fica no seu computador: o OCR do Windows lê o texto, a imagem nunca vai para a internet.", "La cattura attorno al cursore resta sul tuo computer: il testo lo legge l'OCR di Windows, l'immagine non va mai su internet."},

	// подсказка о языках OCR Windows
	"ocr.hint.none":      {"Распознавать нечем: в Windows нет ни русского, ни английского распознавания текста. Параметры → Время и язык → Язык и регион → «Добавить язык» → Русский (и/или English) — галочка «Базовый ввод»/«Оптическое распознавание символов». Потом перезапусти программу.", "Nothing to read with: Windows has neither Russian nor English text recognition. Settings → Time & language → Language & region → “Add a language” → English (and/or Russian) with “Basic typing”/“Optical character recognition”. Then restart the app.", "No hay con qué leer: Windows no tiene reconocimiento de texto ni en ruso ni en inglés. Configuración → Hora e idioma → Idioma y región → «Agregar un idioma» → Inglés (y/o ruso) con «Escritura básica»/«Reconocimiento óptico de caracteres». Luego reinicia la app.", "Nie ma czym czytać: Windows nie ma ani rosyjskiego, ani angielskiego rozpoznawania tekstu. Ustawienia → Czas i język → Język i region → „Dodaj język” → English (i/lub rosyjski) z „Podstawowe wpisywanie”/„Optyczne rozpoznawanie znaków”. Potem uruchom program ponownie.", "Nichts zum Lesen da: Windows hat weder russische noch englische Texterkennung. Einstellungen → Zeit und Sprache → Sprache und Region → „Sprache hinzufügen“ → English (und/oder Russisch) mit „Einfache Eingabe“/„Optische Zeichenerkennung“. Danach das Programm neu starten.", "Okuyacak bir şey yok: Windows'ta ne Rusça ne İngilizce metin tanıma var. Ayarlar → Saat ve dil → Dil ve bölge → “Dil ekle” → English (ve/veya Rusça), “Temel yazma”/“Optik karakter tanıma” ile. Sonra programı yeniden başlat.", "Rien pour lire : Windows n'a ni la reconnaissance de texte russe ni l'anglaise. Paramètres → Heure et langue → Langue et région → « Ajouter une langue » → English (et/ou russe) avec « Saisie de base »/« Reconnaissance optique de caractères ». Ensuite, redémarre le programme.", "Não há com o que ler: o Windows não tem reconhecimento de texto nem em russo nem em inglês. Configurações → Hora e idioma → Idioma e região → “Adicionar um idioma” → English (e/ou russo) com “Digitação básica”/“Reconhecimento óptico de caracteres”. Depois reinicie o programa.", "Non c'è niente con cui leggere: Windows non ha il riconoscimento del testo né russo né inglese. Impostazioni → Data/ora e lingua → Lingua e area geografica → “Aggiungi una lingua” → English (e/o russo) con “Digitazione di base”/“Riconoscimento ottico dei caratteri”. Poi riavvia il programma."},
	"ocr.hint.noRu":      {"Нет русского распознавания текста: тултип русского клиента игры не прочитается. Установи языковой пакет русского (распознавание текста): Параметры → Время и язык → Язык и регион → «Добавить язык» → Русский. Английский клиент читается и так.", "No Russian text recognition: the tooltip of a Russian game client won't be read. Install the Russian language pack (text recognition): Settings → Time & language → Language & region → “Add a language” → Russian. An English client is read as is.", "No hay reconocimiento de texto en ruso: el tooltip del cliente ruso no se leerá. Instala el paquete de idioma ruso (reconocimiento de texto): Configuración → Hora e idioma → Idioma y región → «Agregar un idioma» → Ruso. El cliente en inglés se lee igual.", "Brak rosyjskiego rozpoznawania tekstu: tooltip rosyjskiego klienta gry nie zostanie odczytany. Zainstaluj rosyjski pakiet językowy (rozpoznawanie tekstu): Ustawienia → Czas i język → Język i region → „Dodaj język” → rosyjski. Angielski klient czyta się i tak.", "Keine russische Texterkennung: Der Tooltip eines russischen Spielclients wird nicht gelesen. Installiere das russische Sprachpaket (Texterkennung): Einstellungen → Zeit und Sprache → Sprache und Region → „Sprache hinzufügen“ → Russisch. Ein englischer Client wird auch so gelesen.", "Rusça metin tanıma yok: Rusça oyun istemcisinin ipucu okunmayacak. Rusça dil paketini (metin tanıma) kur: Ayarlar → Saat ve dil → Dil ve bölge → “Dil ekle” → Rusça. İngilizce istemci bu hâliyle de okunur.", "Pas de reconnaissance de texte russe : l'infobulle d'un client de jeu russe ne sera pas lue. Installe le module linguistique russe (reconnaissance de texte) : Paramètres → Heure et langue → Langue et région → « Ajouter une langue » → russe. Un client anglais se lit sans ça.", "Sem reconhecimento de texto em russo: a dica de tela de um cliente russo do jogo não será lida. Instale o pacote de idioma russo (reconhecimento de texto): Configurações → Hora e idioma → Idioma e região → “Adicionar um idioma” → Russo. Um cliente em inglês é lido assim mesmo.", "Manca il riconoscimento del testo russo: il tooltip di un client russo del gioco non verrà letto. Installa il pacchetto lingua russo (riconoscimento del testo): Impostazioni → Data/ora e lingua → Lingua e area geografica → “Aggiungi una lingua” → Russo. Un client inglese si legge comunque."},
	"ocr.hint.noEn":      {"Нет английского распознавания текста: тултип английского клиента игры не прочитается. Параметры → Время и язык → Язык и регион → «Добавить язык» → English (United States). Русский клиент читается и так.", "No English text recognition: the tooltip of an English game client won't be read. Settings → Time & language → Language & region → “Add a language” → English (United States). A Russian client is read as is.", "No hay reconocimiento de texto en inglés: el tooltip del cliente en inglés no se leerá. Configuración → Hora e idioma → Idioma y región → «Agregar un idioma» → English (United States). El cliente ruso se lee igual.", "Brak angielskiego rozpoznawania tekstu: tooltip angielskiego klienta gry nie zostanie odczytany. Ustawienia → Czas i język → Język i region → „Dodaj język” → English (United States). Rosyjski klient czyta się i tak.", "Keine englische Texterkennung: Der Tooltip eines englischen Spielclients wird nicht gelesen. Einstellungen → Zeit und Sprache → Sprache und Region → „Sprache hinzufügen“ → English (United States). Ein russischer Client wird auch so gelesen.", "İngilizce metin tanıma yok: İngilizce oyun istemcisinin ipucu okunmayacak. Ayarlar → Saat ve dil → Dil ve bölge → “Dil ekle” → English (United States). Rusça istemci bu hâliyle de okunur.", "Pas de reconnaissance de texte anglaise : l'infobulle d'un client de jeu anglais ne sera pas lue. Paramètres → Heure et langue → Langue et région → « Ajouter une langue » → English (United States). Un client russe se lit sans ça.", "Sem reconhecimento de texto em inglês: a dica de tela de um cliente em inglês não será lida. Configurações → Hora e idioma → Idioma e região → “Adicionar um idioma” → English (United States). Um cliente russo é lido assim mesmo.", "Manca il riconoscimento del testo inglese: il tooltip di un client inglese del gioco non verrà letto. Impostazioni → Data/ora e lingua → Lingua e area geografica → “Aggiungi una lingua” → English (United States). Un client russo si legge comunque."},
	"ocr.hint.vcRuntime": {"Для точного распознавания установите Microsoft Visual C++ Redistributable (x64) с сайта Microsoft: https://aka.ms/vs/17/release/vc_redist.x64.exe — пока работает распознавание Windows.", "For accurate recognition, install Microsoft Visual C++ Redistributable (x64) from Microsoft: https://aka.ms/vs/17/release/vc_redist.x64.exe — Windows recognition is used for now.", "Para un reconocimiento preciso, instala Microsoft Visual C++ Redistributable (x64) desde Microsoft: https://aka.ms/vs/17/release/vc_redist.x64.exe — por ahora se usa el reconocimiento de Windows.", "Dla dokładnego rozpoznawania zainstaluj Microsoft Visual C++ Redistributable (x64) ze strony Microsoft: https://aka.ms/vs/17/release/vc_redist.x64.exe — na razie działa rozpoznawanie Windows.", "Für genaue Erkennung installiere Microsoft Visual C++ Redistributable (x64) von Microsoft: https://aka.ms/vs/17/release/vc_redist.x64.exe — vorerst läuft die Windows-Erkennung.", "Doğru tanıma için Microsoft Visual C++ Redistributable (x64) paketini Microsoft'tan kur: https://aka.ms/vs/17/release/vc_redist.x64.exe — şimdilik Windows tanıması kullanılıyor.", "Pour une reconnaissance précise, installe Microsoft Visual C++ Redistributable (x64) depuis Microsoft : https://aka.ms/vs/17/release/vc_redist.x64.exe — pour l'instant, c'est la reconnaissance de Windows qui sert.", "Para um reconhecimento preciso, instale o Microsoft Visual C++ Redistributable (x64) do site da Microsoft: https://aka.ms/vs/17/release/vc_redist.x64.exe — por enquanto usa-se o reconhecimento do Windows.", "Per un riconoscimento preciso installa Microsoft Visual C++ Redistributable (x64) dal sito Microsoft: https://aka.ms/vs/17/release/vc_redist.x64.exe — per ora si usa il riconoscimento di Windows."},
	"ocr.hint.check":     {"Не удалось проверить языки распознавания текста Windows — карточка попробует русский и английский наудачу. Подробности в журнале.", "Couldn't check the Windows text recognition languages — the card will try Russian and English anyway. Details are in the log.", "No se pudieron comprobar los idiomas de reconocimiento de Windows: la tarjeta probará ruso e inglés de todos modos. Detalles en el registro.", "Nie udało się sprawdzić języków rozpoznawania tekstu Windows — karta i tak spróbuje rosyjskiego i angielskiego. Szczegóły w dzienniku.", "Die Sprachen der Windows-Texterkennung ließen sich nicht prüfen — die Karte versucht trotzdem Russisch und Englisch. Details im Protokoll.", "Windows metin tanıma dilleri denetlenemedi — kart yine de Rusça ve İngilizceyi deneyecek. Ayrıntılar günlükte.", "Impossible de vérifier les langues de reconnaissance de texte de Windows — la fiche essaiera quand même le russe et l'anglais. Détails dans le journal.", "Não deu para verificar os idiomas de reconhecimento de texto do Windows — a ficha vai tentar russo e inglês mesmo assim. Detalhes no registro.", "Impossibile controllare le lingue di riconoscimento del testo di Windows — la scheda proverà comunque russo e inglese. Dettagli nel registro."},

	// отчёт портала карточки на карту
	"map.why.noTime":    {"🗺 на карту не отправлено: нет времени закрытия", "🗺 not sent to the map: no closing time", "🗺 no enviado al mapa: sin hora de cierre", "🗺 nie wysłano na mapę: brak czasu zamknięcia", "🗺 nicht an die Karte gesendet: keine Schließzeit", "🗺 haritaya gönderilmedi: kapanış zamanı yok", "🗺 pas envoyé à la carte : pas d'heure de fermeture", "🗺 não enviado ao mapa: sem hora de fechamento", "🗺 non inviato alla mappa: manca l'ora di chiusura"},
	"map.why.noPlace":   {"🗺 не знаю, где ты — перейди в другую локацию, программа узнает", "🗺 I don't know where you are — move to another location and the app will know", "🗺 no sé dónde estás: cambia de ubicación y la app lo sabrá", "🗺 nie wiem, gdzie jesteś — przejdź do innej lokacji, a program się dowie", "🗺 ich weiß nicht, wo du bist — wechsle in eine andere Gegend, dann weiß es das Programm", "🗺 nerede olduğunu bilmiyorum — başka bir yere geç, program öğrensin", "🗺 je ne sais pas où tu es — change de lieu et le programme le saura", "🗺 não sei onde você está — vá para outro local e o programa vai saber", "🗺 non so dove sei — spostati in un altro luogo e il programma lo saprà"},
	"map.why.doubt":     {"🗺 не отправлено: название зоны прочиталось неуверенно", "🗺 not sent: the zone name was read with low confidence", "🗺 no enviado: el nombre de la zona no se leyó con seguridad", "🗺 nie wysłano: nazwa strefy odczytana niepewnie", "🗺 nicht gesendet: der Zonenname wurde unsicher gelesen", "🗺 gönderilmedi: bölge adı emin olmadan okundu", "🗺 pas envoyé : le nom de la zone a été lu sans certitude", "🗺 não enviado: o nome da zona foi lido sem certeza", "🗺 non inviato: il nome della zona è stato letto con poca sicurezza"},
	"map.why.notRoad":   {"🗺 не отправлено: это не дороги Авалона", "🗺 not sent: this is not the Roads of Avalon", "🗺 no enviado: no son los Caminos de Avalon", "🗺 nie wysłano: to nie Drogi Avalonu", "🗺 nicht gesendet: das sind nicht die Straßen von Avalon", "🗺 gönderilmedi: burası Avalon Yolları değil", "🗺 pas envoyé : ce ne sont pas les Routes d'Avalon", "🗺 não enviado: não são as Estradas de Avalon", "🗺 non inviato: non sono le Strade di Avalon"},
	"map.why.same":      {"🗺 не отправлено: портал ведёт в эту же зону", "🗺 not sent: the portal leads to this same zone", "🗺 no enviado: el portal lleva a esta misma zona", "🗺 nie wysłano: portal prowadzi do tej samej strefy", "🗺 nicht gesendet: das Portal führt in dieselbe Zone", "🗺 gönderilmedi: portal aynı bölgeye çıkıyor", "🗺 pas envoyé : le portail mène à la même zone", "🗺 não enviado: o portal leva para esta mesma zona", "🗺 non inviato: il portale porta a questa stessa zona"},
	"map.why.unstable":  {"🗺 не отправлено: нестабильный путь — в один конец, время только для твоей группы", "🗺 not sent: an unstable road — one-way, the time is for your party only", "🗺 no enviado: camino inestable — solo ida, el tiempo es solo para tu grupo", "🗺 nie wysłano: niestabilna droga — w jedną stronę, czas tylko dla twojej drużyny", "🗺 nicht gesendet: instabile Straße — nur in eine Richtung, die Zeit gilt nur für deine Gruppe", "🗺 gönderilmedi: dengesiz yol — tek yön, süre yalnızca senin grubun için", "🗺 pas envoyé : route instable — aller simple, le temps ne vaut que pour ton groupe", "🗺 não enviado: estrada instável — só ida, o tempo vale só para o seu grupo", "🗺 non inviato: strada instabile — solo andata, il tempo vale solo per il tuo gruppo"},
	"map.why.notEurope": {"🗺 карта Авалона пока только для европейского сервера", "🗺 the Avalon map is for the Europe server only for now", "🗺 por ahora el mapa de Avalon es solo para el servidor de Europa", "🗺 mapa Avalonu jest na razie tylko dla serwera Europa", "🗺 die Avalon-Karte gibt es vorerst nur für den Europa-Server", "🗺 Avalon haritası şimdilik yalnızca Avrupa sunucusu için", "🗺 la carte d'Avalon n'existe pour l'instant que pour le serveur Europe", "🗺 por enquanto o mapa de Avalon é só para o servidor Europa", "🗺 per ora la mappa di Avalon è solo per il server Europa"},

	// легенда значков (zoneLegend у мака)
	"lg.title":  {"Что значат значки", "What the icons mean", "Qué significan los iconos", "Co znaczą ikony", "Was die Symbole bedeuten", "Simgeler ne anlama geliyor", "Ce que veulent dire les icônes", "O que os ícones significam", "Cosa significano le icone"},
	"lg.chests": {"Сундуки — они же лагеря: сундук бывает только в лагере", "Chests — same as camps: a chest only comes from a camp", "Cofres — o sea campamentos: un cofre solo sale de un campamento", "Skrzynie — to samo co obozy: skrzynia jest tylko w obozie", "Truhen — das sind die Lager: Eine Truhe gibt es nur in einem Lager", "Sandıklar — yani kamplar: sandık yalnızca bir kamptan çıkar", "Coffres — c'est-à-dire camps : un coffre ne vient que d'un camp", "Baús — ou seja, acampamentos: um baú só sai de um acampamento", "Forzieri — cioè accampamenti: un forziere esce solo da un accampamento"},
	"lg.zones":  {"Цвет зоны", "Zone colour", "Color de la zona", "Kolor strefy", "Zonenfarbe", "Bölge rengi", "Couleur de la zone", "Cor da zona", "Colore della zona"},
	"lg.biome":  {"В открытом мире ресурсы задаёт биом зоны: один основной (подсвечен золотом) и два попутных. Сколько там узлов, данные не говорят — только какие.", "In the open world the biome sets the resources: one main (highlighted gold) and two side ones. The data says which, not how many.", "En el mundo abierto el bioma define los recursos: uno principal (en dorado) y dos secundarios. Los datos dicen cuáles, no cuántos.", "W otwartym świecie surowce wyznacza biom strefy: jeden główny (podświetlony złotem) i dwa poboczne. Dane mówią, jakie są, ale nie ile ich jest.", "In der offenen Welt bestimmt das Biom die Ressourcen: eine Hauptressource (golden hervorgehoben) und zwei Nebenressourcen. Die Daten sagen welche, nicht wie viele.", "Açık dünyada kaynakları bölgenin biyomu belirler: bir ana (altınla vurgulanmış) ve iki yan kaynak. Veriler hangileri olduğunu söyler, kaç tane olduğunu değil.", "Dans le monde ouvert, le biome définit les ressources : une principale (surlignée en or) et deux secondaires. Les données disent lesquelles, pas combien.", "No mundo aberto o bioma define os recursos: um principal (destacado em dourado) e dois secundários. Os dados dizem quais, não quantos.", "Nel mondo aperto le risorse le decide il bioma: una principale (evidenziata in oro) e due secondarie. I dati dicono quali, non quante."},
	"lg.res":    {"Ресурсы показаны значками предметов: под каждым — разброс тиров узлов и сколько их всего в зоне.", "Resources use item icons: under each one is the tier range and how many nodes the zone has.", "Los recursos usan iconos de objeto: debajo va el rango de niveles y cuántos nodos hay en la zona.", "Surowce pokazane są ikonami przedmiotów: pod każdą — zakres stopni węzłów i ile ich jest w strefie.", "Ressourcen haben Gegenstandssymbole: Darunter stehen die Stufenspanne und wie viele Knoten die Zone hat.", "Kaynaklar eşya simgeleriyle gösterilir: her birinin altında düğümlerin kademe aralığı ve bölgede toplam kaç tane olduğu yazar.", "Les ressources ont des icônes d'objet : en dessous, la plage de niveaux et le nombre de nœuds de la zone.", "Os recursos usam ícones de item: embaixo de cada um vão a faixa de tiers e quantos nós a zona tem.", "Le risorse hanno icone di oggetto: sotto ognuna c'è l'intervallo di livelli e quanti nodi ha la zona."},
	"lg.camps":  {"Большой соло-лагерь даёт сразу четыре малых сундука, групповой — средний ветеранский, рейдовый — элитный.", "A big solo camp gives four small chests at once, a group camp a medium veteran, a raid camp an elite one.", "Un campamento solo grande da cuatro cofres pequeños; uno grupal, un mediano veterano; uno de incursión, un élite.", "Duży obóz solo daje od razu cztery małe skrzynie, grupowy — średnią weterańską, rajdowy — elitarną.", "Ein großes Solo-Lager gibt gleich vier kleine Truhen, ein Gruppenlager eine mittlere Veteranentruhe, ein Raid-Lager eine Elitetruhe.", "Büyük solo kamp bir kerede dört küçük sandık verir, grup kampı bir orta kıdemli, baskın kampı bir elit sandık.", "Un grand camp solo donne d'un coup quatre petits coffres, un camp de groupe un moyen vétéran, un camp de raid un élite.", "Um acampamento solo grande dá quatro baús pequenos de uma vez; um em grupo, um médio veterano; um de raide, um de elite.", "Un accampamento solo grande dà subito quattro forzieri piccoli, uno di gruppo un medio veterano, uno da raid un forziere d'élite."},

	// настройки карточки
	"sec.zone":           {"КАРТОЧКА ЗОНЫ", "ZONE CARD", "TARJETA DE ZONA", "KARTA STREFY", "ZONENKARTE", "BÖLGE KARTI", "FICHE DE ZONE", "FICHA DA ZONA", "SCHEDA ZONA"},
	"set.hotkey":         {"Кнопка карточки зоны", "Zone card button", "Botón de la tarjeta de zona", "Przycisk karty strefy", "Knopf für die Zonenkarte", "Bölge kartı düğmesi", "Bouton de la fiche de zone", "Botão da ficha da zona", "Pulsante della scheda zona"},
	"key.mouse4":         {"мышь 4 (назад)", "mouse 4 (back)", "ratón 4 (atrás)", "mysz 4 (wstecz)", "Maus 4 (zurück)", "fare 4 (geri)", "souris 4 (précédent)", "mouse 4 (voltar)", "mouse 4 (indietro)"},
	"key.mouse5":         {"мышь 5 (вперёд)", "mouse 5 (forward)", "ratón 5 (adelante)", "mysz 5 (dalej)", "Maus 5 (vor)", "fare 5 (ileri)", "souris 5 (suivant)", "mouse 5 (avançar)", "mouse 5 (avanti)"},
	"key.off":            {"выключена", "off", "desactivado", "wyłączony", "aus", "kapalı", "désactivé", "desligado", "spento"},
	"key.mouse3":         {"средняя кнопка мыши", "middle mouse button", "botón central del ratón", "środkowy przycisk myszy", "mittlere Maustaste", "farenin orta tuşu", "bouton central de la souris", "botão do meio do mouse", "tasto centrale del mouse"},
	"key.set":            {"Назначить", "Set", "Asignar", "Przypisz", "Festlegen", "Ata", "Assigner", "Definir", "Assegna"},
	"key.cancel":         {"Отмена", "Cancel", "Cancelar", "Anuluj", "Abbrechen", "İptal", "Annuler", "Cancelar", "Annulla"},
	"key.turnOff":        {"Выключить", "Turn off", "Desactivar", "Wyłącz", "Ausschalten", "Kapat", "Désactiver", "Desligar", "Spegni"},
	"key.waiting":        {"нажми кнопку…", "press a button…", "pulsa un botón…", "naciśnij przycisk…", "drück eine Taste…", "bir tuşa bas…", "appuie sur un bouton…", "aperte um botão…", "premi un tasto…"},
	"key.recHint":        {"Нажми среднюю или боковую кнопку мыши, сочетание с Ctrl, Alt или Win, или F1–F24 (можно и с Shift), Insert, Page Up/Down, Pause, Scroll Lock. Можно не из окна программы. Esc — отмена.", "Press the middle or a side mouse button, a combo with Ctrl, Alt or Win, or F1–F24 (Shift works too), Insert, Page Up/Down, Pause, Scroll Lock. Works outside the app window too. Esc cancels.", "Pulsa el botón central o uno lateral del ratón, una combinación con Ctrl, Alt o Win, o F1–F24 (también con Shift), Insert, Re Pág/Av Pág, Pausa, Bloq Despl. Funciona también fuera de la ventana. Esc cancela.", "Naciśnij środkowy lub boczny przycisk myszy, skrót z Ctrl, Alt lub Win albo F1–F24 (także z Shift), Insert, Page Up/Down, Pause, Scroll Lock. Działa też poza oknem programu. Esc — anuluj.", "Drück die mittlere oder eine seitliche Maustaste, eine Kombination mit Strg, Alt oder Win, oder F1–F24 (auch mit Umschalt), Einfg, Bild auf/ab, Pause, Rollen. Geht auch außerhalb des Programmfensters. Esc bricht ab.", "Farenin orta ya da yan tuşuna, Ctrl, Alt veya Win ile bir kombinasyona ya da F1–F24 (Shift ile de olur), Insert, Page Up/Down, Pause, Scroll Lock tuşlarına bas. Program penceresinin dışında da çalışır. Esc iptal eder.", "Appuie sur le bouton central ou latéral de la souris, une combinaison avec Ctrl, Alt ou Win, ou F1–F24 (avec Maj aussi), Inser, Page préc./suiv., Pause, Arrêt défil. Marche aussi hors de la fenêtre du programme. Échap annule.", "Aperte o botão do meio ou um lateral do mouse, uma combinação com Ctrl, Alt ou Win, ou F1–F24 (com Shift também), Insert, Page Up/Down, Pause, Scroll Lock. Funciona também fora da janela do programa. Esc cancela.", "Premi il tasto centrale o uno laterale del mouse, una combinazione con Ctrl, Alt o Win, oppure F1–F24 (anche con Maiusc), Ins, Pag su/giù, Pausa, Bloc Scorr. Funziona anche fuori dalla finestra del programma. Esc annulla."},
	"key.needMod":        {"Нужен Ctrl, Alt или Win: голая клавиша сработает в чате игры, а с одним Shift это просто заглавная буква", "Needs Ctrl, Alt or Win: a bare key would fire in the game chat, and with Shift alone it is just a capital letter", "Hace falta Ctrl, Alt o Win: una tecla sola saltaría en el chat del juego, y con solo Shift es una mayúscula", "Potrzebny Ctrl, Alt lub Win: goły klawisz zadziała w czacie gry, a z samym Shift to po prostu wielka litera", "Strg, Alt oder Win nötig: Eine einzelne Taste würde im Spielchat auslösen, und nur mit Umschalt ist es einfach ein Großbuchstabe", "Ctrl, Alt ya da Win gerekli: tek başına bir tuş oyun sohbetinde tetiklenir, yalnızca Shift ile de sadece büyük harf olur", "Il faut Ctrl, Alt ou Win : une touche seule se déclencherait dans le chat du jeu, et avec Maj seul c'est juste une majuscule", "Precisa de Ctrl, Alt ou Win: uma tecla sozinha dispararia no chat do jogo, e só com Shift é apenas uma letra maiúscula", "Serve Ctrl, Alt o Win: un tasto da solo scatterebbe nella chat del gioco, e con il solo Maiusc è solo una lettera maiuscola"},
	"key.timeout":        {"Кнопку не нажали за 10 секунд — осталась прежняя.", "No button pressed in 10 seconds — the old one stays.", "No se pulsó nada en 10 segundos: se queda el anterior.", "W ciągu 10 sekund nic nie naciśnięto — został poprzedni przycisk.", "In 10 Sekunden wurde nichts gedrückt — die alte Taste bleibt.", "10 saniye içinde bir şeye basılmadı — eski tuş kaldı.", "Rien n'a été pressé en 10 secondes — l'ancien bouton reste.", "Nada foi apertado em 10 segundos — fica o botão anterior.", "Nessun tasto premuto in 10 secondi — resta quello di prima."},
	"key.failed":         {"Не удалось записать кнопку: %s", "Couldn't record the button: %s", "No se pudo grabar el botón: %s", "Nie udało się zapisać przycisku: %s", "Die Taste ließ sich nicht aufzeichnen: %s", "Tuş kaydedilemedi: %s", "Impossible d'enregistrer le bouton : %s", "Não deu para gravar o botão: %s", "Impossibile registrare il tasto: %s"},
	"key.unsupported":    {"Записать кнопку можно только в Windows.", "Recording a button works only on Windows.", "Grabar un botón solo funciona en Windows.", "Zapisać przycisk można tylko w Windows.", "Eine Taste aufzeichnen geht nur unter Windows.", "Tuş kaydetme yalnızca Windows'ta çalışır.", "Enregistrer un bouton ne marche que sous Windows.", "Gravar um botão só funciona no Windows.", "Registrare un tasto funziona solo su Windows."},
	"set.hotkeyHint":     {"Наведи курсор на портал дорог в игре и нажми кнопку: программа снимет область у курсора, прочитает тултип и покажет карточку во вкладке «Зона». Нажатие уходит в игру как обычно. Поверх игры рисуется только панель — если выбрать её ниже.", "Point at a roads portal in game and press the button: the app captures the area around the cursor, reads the tooltip and shows the card in the Zone tab. The press still reaches the game. Nothing is drawn over the game unless you pick the panel below.", "Apunta a un portal de los caminos y pulsa el botón: la app captura la zona del cursor, lee el tooltip y muestra la tarjeta en la pestaña Zona. El juego recibe la pulsación igual. No se dibuja nada sobre el juego salvo el panel, si lo eliges abajo.", "Najedź w grze kursorem na portal dróg i naciśnij przycisk: program zrobi zrzut obszaru przy kursorze, odczyta tooltip i pokaże kartę w zakładce „Strefa”. Naciśnięcie trafia do gry jak zwykle. Na grze rysowany jest tylko panel — jeśli wybierzesz go niżej.", "Zeig im Spiel auf ein Straßenportal und drück die Taste: Das Programm nimmt den Bereich um den Cursor auf, liest den Tooltip und zeigt die Karte im Tab „Zone“. Der Druck kommt trotzdem im Spiel an. Über das Spiel wird nichts gezeichnet, außer du wählst unten das Panel.", "Oyunda bir yol portalının üstüne gel ve düğmeye bas: program imlecin etrafını görüntüler, ipucunu okur ve kartı “Bölge” sekmesinde gösterir. Basış her zamanki gibi oyuna da gider. Aşağıda paneli seçmedikçe oyunun üstüne hiçbir şey çizilmez.", "Vise un portail des routes en jeu et appuie sur le bouton : le programme capture la zone autour du curseur, lit l'infobulle et montre la fiche dans l'onglet « Zone ». Le jeu reçoit quand même l'appui. Rien n'est dessiné par-dessus le jeu, sauf si tu choisis le panneau ci-dessous.", "Aponte para um portal das estradas no jogo e aperte o botão: o programa captura a área em volta do cursor, lê a dica de tela e mostra a ficha na aba “Zona”. O jogo recebe o clique normalmente. Nada é desenhado sobre o jogo, a não ser que você escolha o painel abaixo.", "Punta un portale delle strade nel gioco e premi il tasto: il programma cattura l'area attorno al cursore, legge il tooltip e mostra la scheda nella scheda “Zona”. La pressione arriva comunque al gioco. Sopra il gioco non si disegna nulla, a meno che tu non scelga il pannello qui sotto."},
	"set.zoneShow":       {"Способ показа", "How to show it", "Cómo mostrarla", "Sposób pokazywania", "Anzeigeart", "Gösterim şekli", "Mode d'affichage", "Forma de exibir", "Modo di visualizzazione"},
	"show.notify":        {"Уведомление", "Notification", "Notificación", "Powiadomienie", "Benachrichtigung", "Bildirim", "Notification", "Notificação", "Notifica"},
	"show.panel":         {"Панель поверх игры", "Panel over the game", "Panel sobre el juego", "Panel nad grą", "Panel über dem Spiel", "Oyunun üstünde panel", "Panneau sur le jeu", "Painel sobre o jogo", "Pannello sopra il gioco"},
	"show.off":           {"Выключено", "Off", "Desactivado", "Wyłączone", "Aus", "Kapalı", "Désactivé", "Desligado", "Spento"},
	"show.notifyHint":    {"Баннер рисует сама Windows, как уведомление любой программы, — не мы поверх игры. В полноэкранной игре Windows может прятать уведомления («Не беспокоить» во время игры) — тогда карточка только во вкладке.", "Windows draws the banner like any app's notification — not us over the game. In a fullscreen game Windows may hold notifications back (“Do not disturb” while gaming) — then the card is only in the tab.", "El aviso lo dibuja Windows, como el de cualquier app, no nosotros sobre el juego. En un juego a pantalla completa Windows puede ocultarlos («No molestar» al jugar): entonces la tarjeta solo está en la pestaña.", "Baner rysuje sam Windows, jak powiadomienie każdego programu — nie my na grze. W grze pełnoekranowej Windows może wstrzymywać powiadomienia („Nie przeszkadzać” podczas gry) — wtedy karta jest tylko w zakładce.", "Das Banner zeichnet Windows selbst, wie die Benachrichtigung jedes Programms — nicht wir über dem Spiel. In einem Vollbildspiel hält Windows Benachrichtigungen eventuell zurück („Nicht stören“ beim Spielen) — dann ist die Karte nur im Tab.", "Afişi, herhangi bir programın bildirimi gibi Windows kendisi çizer — oyunun üstüne biz değil. Tam ekran oyunda Windows bildirimleri bekletebilir (oyun sırasında “Rahatsız etmeyin”) — o zaman kart yalnızca sekmede olur.", "La bannière est dessinée par Windows lui-même, comme la notification de n'importe quel programme — pas par nous sur le jeu. Dans un jeu en plein écran, Windows peut retenir les notifications (« Ne pas déranger » pendant le jeu) — la fiche n'est alors que dans l'onglet.", "O banner é desenhado pelo próprio Windows, como a notificação de qualquer programa — não por nós sobre o jogo. Num jogo em tela cheia o Windows pode segurar notificações (“Não incomodar” ao jogar) — aí a ficha fica só na aba.", "Il banner lo disegna Windows stesso, come la notifica di qualsiasi programma — non noi sopra il gioco. In un gioco a schermo intero Windows può trattenere le notifiche (“Non disturbare” durante il gioco) — allora la scheda è solo nella scheda."},
	"show.panelHint":     {"Маленькая панель в углу экрана с игрой на несколько секунд. Фокус не забирает, клики проходят в игру. Видна, когда игра в окне или в «окне без рамки»; в полноэкранном (эксклюзивном) режиме Windows отдаёт экран игре целиком и панели не видно — переключи игру в «окно без рамки».", "A small panel in a corner of the game's screen for a few seconds. It doesn't take focus, clicks go through to the game. Visible when the game runs windowed or borderless; in exclusive fullscreen Windows gives the whole screen to the game and the panel can't be seen — switch the game to borderless window.", "Un panel pequeño en una esquina de la pantalla del juego durante unos segundos. No quita el foco y los clics pasan al juego. Se ve con el juego en ventana o en ventana sin bordes; en pantalla completa exclusiva Windows da toda la pantalla al juego y el panel no se ve: cambia el juego a ventana sin bordes.", "Mały panel w rogu ekranu z grą na kilka sekund. Nie zabiera fokusu, kliknięcia przechodzą do gry. Widać go, gdy gra działa w oknie lub w „oknie bez ramki”; w trybie pełnoekranowym (wyłącznym) Windows oddaje grze cały ekran i panelu nie widać — przełącz grę na „okno bez ramki”.", "Ein kleines Panel in einer Ecke des Spielbildschirms für ein paar Sekunden. Es nimmt keinen Fokus, Klicks gehen ans Spiel durch. Sichtbar, wenn das Spiel im Fenster oder rahmenlosen Fenster läuft; im exklusiven Vollbild gibt Windows den ganzen Bildschirm dem Spiel und das Panel ist nicht zu sehen — stell das Spiel auf rahmenloses Fenster um.", "Oyun ekranının bir köşesinde birkaç saniyelik küçük bir panel. Odağı almaz, tıklamalar oyuna geçer. Oyun pencerede ya da kenarlıksız pencerede çalışırken görünür; özel tam ekranda Windows tüm ekranı oyuna verir ve panel görünmez — oyunu kenarlıksız pencere moduna al.", "Un petit panneau dans un coin de l'écran du jeu pendant quelques secondes. Il ne prend pas le focus, les clics passent au jeu. Visible quand le jeu est en fenêtre ou en fenêtre sans bordure ; en plein écran exclusif, Windows donne tout l'écran au jeu et le panneau ne se voit pas — passe le jeu en fenêtre sans bordure.", "Um painel pequeno num canto da tela do jogo por alguns segundos. Não rouba o foco e os cliques passam para o jogo. Aparece quando o jogo está em janela ou em janela sem bordas; em tela cheia exclusiva o Windows dá a tela inteira ao jogo e o painel não aparece — mude o jogo para janela sem bordas.", "Un piccolo pannello in un angolo dello schermo del gioco per qualche secondo. Non ruba il focus, i clic passano al gioco. Si vede quando il gioco è in finestra o in finestra senza bordi; a schermo intero esclusivo Windows dà tutto lo schermo al gioco e il pannello non si vede — passa il gioco a finestra senza bordi."},
	"show.offHint":       {"Карточка только во вкладке «Зона».", "The card is only in the Zone tab.", "La tarjeta solo está en la pestaña Zona.", "Karta jest tylko w zakładce „Strefa”.", "Die Karte gibt es nur im Tab „Zone“.", "Kart yalnızca “Bölge” sekmesinde.", "La fiche n'est que dans l'onglet « Zone ».", "A ficha fica só na aba “Zona”.", "La scheda è solo nella scheda “Zona”."},
	"set.corner":         {"Угол экрана", "Screen corner", "Esquina de la pantalla", "Róg ekranu", "Bildschirmecke", "Ekran köşesi", "Coin de l'écran", "Canto da tela", "Angolo dello schermo"},
	"corner.topLeft":     {"слева сверху", "top left", "arriba a la izquierda", "lewy górny", "oben links", "sol üst", "en haut à gauche", "em cima à esquerda", "in alto a sinistra"},
	"corner.topRight":    {"справа сверху", "top right", "arriba a la derecha", "prawy górny", "oben rechts", "sağ üst", "en haut à droite", "em cima à direita", "in alto a destra"},
	"corner.bottomLeft":  {"слева снизу", "bottom left", "abajo a la izquierda", "lewy dolny", "unten links", "sol alt", "en bas à gauche", "embaixo à esquerda", "in basso a sinistra"},
	"corner.bottomRight": {"справа снизу", "bottom right", "abajo a la derecha", "prawy dolny", "unten rechts", "sağ alt", "en bas à droite", "embaixo à direita", "in basso a destra"},
	"set.overlaySec":     {"Секунд на экране", "Seconds on screen", "Segundos en pantalla", "Sekund na ekranie", "Sekunden auf dem Bildschirm", "Ekranda kalma süresi, sn", "Secondes à l'écran", "Segundos na tela", "Secondi sullo schermo"},
	"nt.what":            {"Что показывать", "What to show", "Qué mostrar", "Co pokazywać", "Was anzeigen", "Neler gösterilsin", "Quoi afficher", "O que mostrar", "Cosa mostrare"},
	"nt.chestsFirst":     {"сундуки сверху", "chests first", "cofres primero", "skrzynie najpierw", "Truhen zuerst", "önce sandıklar", "coffres d'abord", "baús primeiro", "prima i forzieri"},
	"nt.resFirst":        {"ресурсы сверху", "resources first", "recursos primero", "surowce najpierw", "Ressourcen zuerst", "önce kaynaklar", "ressources d'abord", "recursos primeiro", "prima le risorse"},
	"nt.chests":          {"Сундуки", "Chests", "Cofres", "Skrzynie", "Truhen", "Sandıklar", "Coffres", "Baús", "Forzieri"},
	"nt.res":             {"Ресурсы", "Resources", "Recursos", "Surowce", "Ressourcen", "Kaynaklar", "Ressources", "Recursos", "Risorse"},
	"nt.dng":             {"Подземелья", "Dungeons", "Mazmorras", "Lochy", "Dungeons", "Zindanlar", "Donjons", "Masmorras", "Dungeon"},
	"nt.portal":          {"Портал и время", "Portal and time", "Portal y tiempo", "Portal i czas", "Portal und Zeit", "Portal ve süre", "Portail et temps", "Portal e tempo", "Portale e tempo"},
	"set.blackWarn":      {"Предупреждать о чёрном экране", "Warn about the black screen", "Avisar de la pantalla negra", "Ostrzegaj o czarnym ekranie", "Vor dem Schwarzbild warnen", "Siyah ekran için uyar", "Avertir de l'écran noir", "Avisar sobre a tela preta", "Avvisa dello schermo nero"},
	"set.blackWarnHint":  {"Новый сервер не ответил за 2 с после перехода — уведомление «Сервер зоны не отвечает». В карточке портала — сколько раз чёрный экран был в твоих переходах в эту зону (от трёх переходов).", "The new server hasn't answered 2 s after a zone change — a “Zone server not responding” notification. The portal card shows how often you got a black screen moving into that zone (from three moves on).", "Si el nuevo servidor no responde 2 s después de cambiar de zona, aviso «El servidor de la zona no responde». La tarjeta del portal muestra cuántas veces tuviste pantalla negra al entrar en esa zona (a partir de tres pasos).", "Nowy serwer nie odpowiedział w ciągu 2 s po przejściu — powiadomienie „Serwer strefy nie odpowiada”. Na karcie portalu — ile razy czarny ekran był w twoich przejściach do tej strefy (od trzech przejść).", "Antwortet der neue Server 2 s nach einem Zonenwechsel nicht, kommt die Benachrichtigung „Zonenserver antwortet nicht“. Die Portalkarte zeigt, wie oft du beim Wechsel in diese Zone ein Schwarzbild hattest (ab drei Wechseln).", "Yeni sunucu bölge değişiminden 2 sn sonra yanıt vermezse “Bölge sunucusu yanıt vermiyor” bildirimi gelir. Portal kartında, o bölgeye geçişlerinde kaç kez siyah ekran olduğu gösterilir (üç geçişten itibaren).", "Si le nouveau serveur ne répond pas 2 s après un changement de zone, notification « Le serveur de la zone ne répond pas ». La fiche du portail montre combien de fois tu as eu un écran noir en entrant dans cette zone (à partir de trois passages).", "Se o novo servidor não responder 2 s depois de trocar de zona, vem a notificação “O servidor da zona não responde”. A ficha do portal mostra quantas vezes você teve tela preta ao entrar nessa zona (a partir de três passagens).", "Se il nuovo server non risponde 2 s dopo un cambio di zona, arriva la notifica “Il server della zona non risponde”. La scheda del portale mostra quante volte hai avuto lo schermo nero entrando in quella zona (da tre passaggi in su)."},

	// уведомление о чёрном экране (Go)
	"msg.blackTitle": {"Сервер зоны не отвечает", "Zone server not responding", "El servidor de la zona no responde", "Serwer strefy nie odpowiada", "Zonenserver antwortet nicht", "Bölge sunucusu yanıt vermiyor", "Le serveur de la zone ne répond pas", "O servidor da zona não responde", "Il server della zona non risponde"},
	"msg.blackBody":  {"Похоже на чёрный экран: новый сервер молчит после подключения.", "Looks like a black screen: the new server is silent after connecting.", "Parece pantalla negra: el nuevo servidor no responde tras conectar.", "Wygląda na czarny ekran: nowy serwer milczy po połączeniu.", "Sieht nach Schwarzbild aus: Der neue Server schweigt nach dem Verbinden.", "Siyah ekran gibi görünüyor: yeni sunucu bağlandıktan sonra sessiz.", "Ça ressemble à un écran noir : le nouveau serveur reste muet après la connexion.", "Parece tela preta: o novo servidor está calado depois de conectar.", "Sembra uno schermo nero: il nuovo server tace dopo la connessione."},
	"msg.blackFrom":  {"Похоже на чёрный экран: новый сервер молчит после перехода из %s.", "Looks like a black screen: the new server is silent after leaving %s.", "Parece pantalla negra: el nuevo servidor no responde tras salir de %s.", "Wygląda na czarny ekran: nowy serwer milczy po wyjściu z %s.", "Sieht nach Schwarzbild aus: Der neue Server schweigt nach dem Verlassen von %s.", "Siyah ekran gibi görünüyor: yeni sunucu %s bölgesinden çıktıktan sonra sessiz.", "Ça ressemble à un écran noir : le nouveau serveur reste muet après avoir quitté %s.", "Parece tela preta: o novo servidor está calado depois de sair de %s.", "Sembra uno schermo nero: il nuovo server tace dopo l'uscita da %s."},
}
